### ISSUE TITLE
Audio didn't play when app in background, but video works perfect 

### ISSUE THREAD

**Issue by CAMOBAP795** [googlecast/CastRemoteDisplay-android#11]
Audio didn't play when app closed, but video works perfect 

Is this expected behavior or a bug?
Maybe some workaround for this exists?

**Comment by CAMOBAP795** [comment]
The same bug reported to official tracker SDK tracker https://code.google.com/p/google-cast-sdk/issues/detail?id=756&thanks=756&ts=1454923296

**Comment by entertailion** [comment]
This is by design. Since audio is captured at the system level on Android, when another app like the phone app comes to the foreground, the audio isn't sent to the Cast device.

**Comment by CAMOBAP795** [comment]
@entertailion, thanks for answer.

Maybe there is some workaround because I didn't want to capture audio at system level, I just wanna to stream audio from my inapp `MediaPlayer`?

**Comment by entertailion** [comment]
This is a limitation of the Android media framework. There is no workaround.
