### ISSUE TITLE
onCreatePresentation never calls

### ISSUE THREAD

**Issue by Zo2m4bie** [googlecast/CastRemoteDisplay-android#13]
Hi. I downloaded  latest code from github, compile it but my problem is that [onCreatePresentation](https://github.com/googlecast/CastRemoteDisplay-android/blob/master/src/com/example/castremotedisplay/PresentationService.java#L58) in [PresentationService](https://github.com/googlecast/CastRemoteDisplay-android/blob/master/src/com/example/castremotedisplay/PresentationService.java) never calls. But [onDismissPresentation](https://github.com/googlecast/CastRemoteDisplay-android/blob/master/src/com/example/castremotedisplay/PresentationService.java#L63)  calls when I stop casting. I use chromecast 2

**Comment by Zo2m4bie** [comment]
It's my bad. I had wrong cast id

**Comment by ryansites310** [comment]
@Zo2m4bie did you mean application id? I am having same issue, OnCreatePresentation is is not getting called.

**Comment by melmor** [comment]
melmor25@live.camw
