### ISSUE TITLE
How to mirror all screen/ui from mobile to tv?

### ISSUE THREAD

**Issue by ananth10** [googlecast/CastRemoteDisplay-android#17]
I need to mirror each and every ui screen from mobile to tv. can anyone tell me how to do it?

**Comment by entertailion** [comment]
There is no API to support that. The user can use the system level mirroring feature to cast the screen.

**Comment by ananth10** [comment]
@entertailion . Thanks for reply . can you explain me what is system level mirroring? and whats the limitation? and Which API should i use?

**Comment by entertailion** [comment]
System level mirroring is the feature the user can use to mirror the screen to a remote device. There is no API for that.

**Comment by ananth10** [comment]
@entertailion . Thanks. got it now. so i guess system level mirror implemented in google home app. am i right?

**Comment by entertailion** [comment]
The Cast protocol is implemented in Google Play services.

**Comment by ananth10** [comment]
@entertailion Ohh..Thats great!!
