### ISSUE TITLE
Design is  not mirroring exact like layout in mobile 

### ISSUE THREAD

**Issue by ananth10** [googlecast/CastRemoteDisplay-android#19]
When i mirroring mobile to TV . i am not getting exact design on TV . but design looks good on mobile. below i have attached the both screenshots. kindly check it .and please tell me what mistake i have done. and suggest me how to do it?

![design_looks_on_mobile](https://cloud.githubusercontent.com/assets/13381242/24188211/7fac3b40-0f06-11e7-9856-1b245b939054.png)
![design_looks_on_tv](https://cloud.githubusercontent.com/assets/13381242/24188230/9056fafc-0f06-11e7-8b7e-785f7b21d6a4.jpg)

**Comment by entertailion** [comment]
The display resolution of the Cast device is 720p, so you have to design your rendering to use those dimensions and not the dimensions of the phone.

**Comment by ananth10** [comment]
@entertailion .okay got it.. Thanks for the info.

**Comment by ananth10** [comment]
@entertailion  but when i view rendering layout in "Device editor"(selected size is tv720p) . it looks good.
can you exactly tell me in which layout should i design(layout-sw720dp or layout-xlarge or layout-xlarge-land) ? it would be better for me.

**Comment by ananth10** [comment]
@entertailion **so you have to design your rendering to use those dimensions and not the dimensions of the phone.** how to do it? . can you tell me please?
