### ISSUE TITLE
How to disconnect cast programmatically?

### ISSUE THREAD

**Issue by ananth10** [googlecast/CastRemoteDisplay-android#21]
I need to disconnect cast when activity destroy. is it possible? and is there a way to connect to cast device when activity created?

**Comment by entertailion** [comment]
The UX guidelines require that the user selects the device to connect to. If you want to support automatic reconnection logic, then either use CCL or follow our guidelines: https://developers.google.com/cast/docs/android_sender_integrate#automatic_reconnection
