### ISSUE TITLE
Video Conference Application - Cast Audio to TV Screen

### ISSUE THREAD

**Issue by kvikrama** [googlecast/CastRemoteDisplay-android#25]
Hi ,

  We are building video Conferencing application and would like to cast Video and Audio to TV Screen. We have been successful in casting Screen to TV, but audio is not getting cast.

We understand that phone call audio's are not routed to TV.
But this is a video conference application. What is the work way forward or work around ?

**Comment by entertailion** [comment]
For Android, the audio is captured on a system level: https://developer.android.com/reference/android/media/MediaRecorder.AudioSource.html#REMOTE_SUBMIX

**Comment by kvikrama** [comment]
@entertailion does it mean that in video conferencing case, audio cannot be presented in the display ?

**Comment by entertailion** [comment]
It can but only audio from that level will be sent to the remote device.

**Comment by kvikrama** [comment]
@entertailion request you to give us some references.

**Comment by kvikrama** [comment]
@entertailion @google-admin 
As mentioned in https://github.com/twilio/video-quickstart-android/issues/98#issuecomment-302997797 , do you think it's within google cast SDK items ?

**Comment by entertailion** [comment]
You can file a feature request: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc

**Comment by hakeemsyd** [comment]
Hello @kvikrama, I ran into same issue. Curious to know what did you ended up doing?
