### ISSUE TITLE
How to develop a Cast receiver application using Android?

### ISSUE THREAD

**Issue by Ranjith1992** [googlecast/CastRemoteDisplay-android#28]
I read about cast receivers from the below link. https://developers.google.com/cast

From here I found some sample receiver applications in JS and HTML.

Actually I need to develop a cast receiver application in android. But i didn't get any sample code or tutorials for this.

Is it possible to develop a cast receiver using android? If yes, what do I need and where do I get references ?

Any overview on this would be highly appreciated :)

Thanks!

**Comment by entertailion** [comment]
A cast receiver is a HTML application. You cannot developer a receiver in Android.

**Comment by Ranjith1992** [comment]
@entertailion  Thanks for the response.

I have some more queries in this case.

1. Can I run this cast receiver (HTML application) in Chrome browser in Android OS ? 

2. Whether Chrome OS is required for running cast receiver (HTML application) ?

3. I found one application named cheapcast from the below link.
   https://forum.xda-developers.com/showthread.php?t=2402387

Cast receiver functionality worked in Android using this application.

I was wondering how cheapcast application worked in my Android os, since cast receiver is an HTML application. Could you please shed some light on this behaviour.


I look forward to hearing from you soon.

**Comment by entertailion** [comment]
1. No.
2. No.
3. Only the Cast SDK and Cast devices are supported.

**Comment by Ranjith1992** [comment]
Thank you @entertailion for providing the clarifications.
Regarding item 3 (Only the Cast SDK and Cast devices are supported), is it possible to make an Android or Linux device as a cast receiving device?

As per Google cast SDK documentation, we can write custom receivers. https://developers.google.com/cast/docs/caf_receiver_overview

Our intention is to write our own receiver in Android and/or Linux system.

**Comment by entertailion** [comment]
The Cast SDK doesn't allow you to create your own receiver device.
