### ISSUE TITLE
Support on android things.

### ISSUE THREAD

**Issue by akhileshAwasthi** [googlecast/CastRemoteDisplay-android#29]
I recentlty tried to run this sample on android things **developer preview 0.6** on **Pico i.MX7 Dual Development Board** (with modification required such as library for android things etc.), but it was unable to fetch the list of cast devices available on network. However, this very sample worked on my emulator and real device seamlessly. Any idea why ?

**Comment by entertailion** [comment]
Android Things does not include the GMS core module for a Cast sender.

**Comment by rinav** [comment]
Can we sideload or flash gapps on Things, so that gms core module gets installed on it?
