### ISSUE TITLE
Gradle error when trying to build

### ISSUE THREAD

**Issue by isaacwalkercox** [googlecast/CastRemoteDisplay-android#30]
I keep getting this gradle error when trying to build this project:

Error:Unsupported method: BaseConfig.getApplicationIdSuffix().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.

What is causing this?

**Comment by entertailion** [comment]
You need to upgrade your version of Gradle: https://stackoverflow.com/questions/44546849/unsupported-method-baseconfig-getapplicationidsuffix

**Comment by isaacwalkercox** [comment]
No it told me that I needed 2.2 when I tried to do that. 

⁣Sent from TypeApp ​
