### ISSUE TITLE
Chromecast on the Samsung Tab E doesn't connect

### ISSUE THREAD

**Issue by degemot** [googlecast/CastRemoteDisplay-android#33]
I’m using chromecast to cast info to the TV screen. After the successful registration of the application and the chromecast device itself, I successfully got to connect to the TV and casted data using the phone with api 27. At the same time I could not connect to the TV via the tablet using the same application. The tablet have api 19 and I have installed non official Android with api 27 which wasn’t successful either.

Both the phone and the table are successfully casts everything using standard apps like Youtube and etc.

When I’m using the tablet the error happens when I call function CastRemoteDisplayLocalService.startService and it calls onRemoteDisplaySessionError. For a few second the TV screen becomes black but the tablet shows me a message that the connection is lost.

This is the log which I got:

> D/MainActivity: onRouteSelected D/Rasul: CreatedPresentation0
> 
> V/MediaRouter: Dispatching route change: UserRouteInfo{ name=Bedroom TV, description=Chromecast, status=null, category=RouteCategory{ name=Devices types=ROUTE_TYPE_USER groupable=false }, supportedTypes=ROUTE_TYPE_USER , presentationDisplay=null }
> 
> V/MediaRouter: Dispatching route change: UserRouteInfo{ name=Bedroom TV, description=Chromecast, status=null, category=RouteCategory{ name=Devices types=ROUTE_TYPE_USER groupable=false }, supportedTypes=ROUTE_TYPE_USER , presentationDisplay=null }
> 
> V/MediaRouter: Dispatching route change: UserRouteInfo{ name=Bedroom TV, description=Chromecast, status=null, category=RouteCategory{ name=Devices types=ROUTE_TYPE_USER groupable=false }, supportedTypes=ROUTE_TYPE_USER , presentationDisplay=null }
> 
> V/MediaRouter: Dispatching route change: UserRouteInfo{ name=Bedroom TV, description=Chromecast, status=null, category=RouteCategory{ name=Devices types=ROUTE_TYPE_USER groupable=false }, supportedTypes=ROUTE_TYPE_USER , presentationDisplay=null }
> 
> V/MediaRouter: Dispatching route change: UserRouteInfo{ name=Bedroom TV, description=Chromecast, status=null, category=RouteCategory{ name=Devices types=ROUTE_TYPE_USER groupable=false }, supportedTypes=ROUTE_TYPE_USER , presentationDisplay=null }
> 
> Dispatching route change: UserRouteInfo{ name=Bedroom TV, description=Chromecast, status=null, category=RouteCategory{ name=Devices types=ROUTE_TYPE_USER groupable=false }, supportedTypes=ROUTE_TYPE_USER , presentationDisplay=null } W/CastRemoteDisplayLocalService: [Instance: com.google.android.gms.cast.CastRemoteDisplayLocalService$10@b44de89] ConnectionSuspended 1 I/MediaRouter: Unselecting the current route because it is no longer selectable: MediaRouter.RouteInfo{ uniqueId=com.google.android.gms/.cast.media.CastMediaRouteProviderService:1cc4d2c9976ead58a32b1075cdd51184, name=Bedroom TV, description=Chromecast, iconUri=null, enabled=true, connecting=false, connectionState=2, canDisconnect=false, playbackType=1, playbackStream=-1, deviceType=1, volumeHandling=1, volume=20, volumeMax=20, presentationDisplayId=-1, extras=Bundle[mParcelledData.dataSize=868], settingsIntent=null, providerPackageName=com.google.android.gms }
> 

> E/CastRemoteDisplayLocalService: Connection was not successful\
> 
> E/CAST: result - null
> 
> E/CastRemoteDisplayLocalService: Unable to stop the remote display as the API client is not ready

> 
> V/MediaRouter: Selecting route: RouteInfo{ name=Tablet, description=null, status=null, category=RouteCategory{ name=null types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null } V/MediaRouter: Dispatching route change: UserRouteInfo{ name=Bedroom TV, description=Chromecast, status=null, category=RouteCategory{ name=Devices types=ROUTE_TYPE_USER groupable=false }, supportedTypes=ROUTE_TYPE_USER , presentationDisplay=null }
> 
> Removing route: UserRouteInfo{ name=Bedroom TV, description=Chromecast, status=null, category=RouteCategory{ name=Devices types=ROUTE_TYPE_USER groupable=false }, supportedTypes=ROUTE_TYPE_USER , presentationDisplay=null }

I don’t really know what to do next. Is it even possible?

**Comment by entertailion** [comment]
You need to have Google Play services installed for Cast to work. Apps like YouTube and Netflix use their own discovery and control protocols that are not based on Cast.
