### ISSUE TITLE
When backpress after start casting,  getting black screen

### ISSUE THREAD

**Issue by mohitchauhan** [googlecast/CastRemoteDisplay-android#34]
When I am pressing back button after starting cast. TV screen starts appearing black. However its working fine in case  I press the Home button and even kill activity from recent.

**Comment by entertailion** [comment]
You can file an issue: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc
But the Remote Display API has been deprecated.
