### ISSUE TITLE
Just crashed on Nexus 7 2012

### ISSUE THREAD

**Issue by TheFakeMontyOnTheRun** [googlecast/CastRemoteDisplay-android#4]
Hello, I'm really kind of lost on what happened, and I can't really provide much data, but this sample just crashed on my Nexus 7 (2012), running Lollipop 5.1. My Chromecast is also fully updated.

The crash happens after I press play and select my cast device. The TV screen goes full black and finally the app crashes.

Here is the stack trace:
06-20 23:15:45.787  22374-22982/? E/AndroidRuntime﹕ FATAL EXCEPTION: GLThread 966
    Process: com.example.castremotedisplay, PID: 22374
    java.lang.IllegalArgumentException
            at com.google.android.gles_jni.EGLImpl._eglCreateContext(Native Method)
            at com.google.android.gles_jni.EGLImpl.eglCreateContext(EGLImpl.java:54)
            at android.opengl.GLSurfaceView$DefaultContextFactory.createContext(GLSurfaceView.java:766)
            at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1029)
            at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1400)
            at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
If is there of any help, those messages were displayed in logcat before the crash:

06-20 23:15:45.370  14922-22964/? E/ACodec﹕ Encoder could not be configured to emit SPS/PPS before IDR frames. (err -2147483648)
06-20 23:15:45.370  14922-22964/? E/ACodec﹕ [OMX.Nvidia.h264.encoder] configureCodec returning error -2147483648
06-20 23:15:45.371  14922-22964/? E/ACodec﹕ signalError(omxError 0x80001001, internalError -2147483648)
06-20 23:15:45.371  14922-22963/? E/MediaCodec﹕ Codec reported err 0x80001001, actionCode 0, while in state 3
06-20 23:15:45.371  14922-22960/? E/MediaCodec﹕ configure failed with err 0x80001001, resetting...
06-20 23:15:45.372  14922-22964/? I/OMXClient﹕ Using client-side OMX mux.
06-20 23:15:45.379  14922-22960/? I/Converter﹕ We going to manually prepend SPS and PPS to IDR frames.
06-20 23:15:45.381    124-22967/? E/OMXNodeInstance﹕ setParameter(34:Nvidia.h264.encoder, OMX.google.android.index.storeMetaDataInBuffers(0x7fc00007): Output:1 en=0 GB=0) ERROR: BadParameter(0x80001005)
06-20 23:15:45.381  14922-22964/? E/ACodec﹕ [OMX.Nvidia.h264.encoder] storeMetaDataInBuffers (output) failed w/ err -2147483648
06-20 23:15:45.382  14922-22964/? W/ACodec﹕ do not know color format 0x7f000789 = 2130708361
06-20 23:15:45.401      124-124/? D/NvOsDebugPrintf﹕ NvMMLiteOpen : Block : BlockType = 4
06-20 23:15:45.402      124-124/? D/NvOsDebugPrintf﹕ NvRmPowerModuleClockControl on MOD[29] INST[0]
06-20 23:15:45.403      124-124/? D/NvOsDebugPrintf﹕ NvRmModuleResetWithHold deassert MOD[29] INST[0]
06-20 23:15:45.403      124-124/? D/NvOsDebugPrintf﹕ NvMMLiteBlockCreate : Block : BlockType = 4
06-20 23:15:45.403  14922-22964/? I/ACodec﹕ setupVideoEncoder succeeded
06-20 23:15:45.403      124-124/? E/OMXNodeInstance﹕ setParameter(34:Nvidia.h264.encoder, OMX.google.android.index.enableAndroidNativeBuffers(0x7fc00004): Output:1 en=0) ERROR: BadParameter(0x80001005)
...
-------------------------
Also decided to try on my Motorola Moto E (first gen, still on Kitkat 4.4.4.) - it didn't crash, but wasn't functional either, stuck on the black screen. The only relevant message on logcat was this:

06-20 23:28:11.910    291-12404/? E/OMX-VENC-720p﹕ set_parameter: metamode is valid for input port only
06-20 23:28:11.911    291-12404/? E/OMXNodeInstance﹕ OMX_SetParameter() failed for StoreMetaDataInBuffers: 0x8000101a
06-20 23:28:11.911   2704-15634/? E/ACodec﹕ [OMX.qcom.video.encoder.avc] storeMetaDataInBuffers (output) failed w/ err -2147483648
06-20 23:28:11.912     291-8500/? E/OMX-VENC-720p﹕ WARNING: Unsupported Color format [2130708361]
06-20 23:28:11.912     291-8500/? E/OMX-VENC-720p﹕ C2D init is successful
06-20 23:28:11.912      291-843/? E/OMX-VENC-720p﹕ WARNING: Unsupported Color format [2130708361]
...
-------------------------
Finally, I couldn't help but notice that you're using ActionBarActivity instead of AppCompatActivity? Changed it here, but the crash didn't go away.

I will dive deeper into the code tomorrow and try to provide more information (since I'm trying to learn how to use it).

**Comment by TheFakeMontyOnTheRun** [comment]
BTW, managed to try again a new TV and the sound came thru, but no luck regarding the image.
Also, forgot to mention: with my Kitkat device, the change color button did nothing (at least it didn't crash).
I tried mapping the code today, but couldn't get too far. My next plan is to replace the second screen view with something simpler.

**Comment by entertailion** [comment]
Is mirroring working for you on your devices?

**Comment by TheFakeMontyOnTheRun** [comment]
The Moto E doesn't seem to work - I got a black screen. But I managed to Cast Screen quite well with the Nexus.
One thing caught my attention, actually:
Motion Tennis (that game showcased during IO) doesn't seem to work that well on the Nexus. Sometimes it get confused on what it should display on each screen, and times it confused the screen dimensions.

Maybe it's the nexus? What else should I try?

**Comment by entertailion** [comment]
Can you provide us with a complete log while running the Remote Display sample app on the Nexus: https://support.google.com/cast-developer/contact/google_cast_contact_us?hl=en&rd=1

**Comment by TheFakeMontyOnTheRun** [comment]
Sure! Sorry it took me so long to answer.
I will make sure it's the pristine code (no changes whatsoever)

**Comment by TheFakeMontyOnTheRun** [comment]
(BTW, I was unsure what to fill for Developer Id, so I took the big number that displays at my Play Developer Console URL and used that. It is the right number?)

**Comment by entertailion** [comment]
Thats fine.

**Comment by entertailion** [comment]
PresentationService has been updated to fall back to no anti-aliasing for devices that don't support that.
