### ISSUE TITLE
Will not pop up with Chromecast chooser

### ISSUE THREAD

**Issue by Sarkie** [googlecast/CastRemoteDisplay-android#5]
Hi,

I created an app of type : Remote Display Receiver

I had my device to the site too.

No matter what I do, there is no pop up asking for me to choose the Chromecast device, hence I can't seem to progress, tried on 2 devices and tried with 2 example apps.

Is there a bug in Google Play Services or something?

Cheers.

**Comment by entertailion** [comment]
Restart your Chromecast device to get the latest configuration from the Developer Console.

**Comment by Sarkie** [comment]
@entertailion did that twice, third time worked! I'm going to leave this open for Google.

Thanks!
