### ISSUE TITLE
Multiple Instances of PresentationService?

### ISSUE THREAD

**Issue by holyspidoo** [googlecast/CastRemoteDisplay-android#9]
I noticed that when disconnecting from Chromecast, I would always see this in logcat:
E/CastRemoteDisplayLocalService: Service is already being stopped

Upon looking at the java heap dump hprof, I see 3 counts of PresentationService. Is this normal?
This is in your stock sample app. Is this normal behavior?

In my app, since there are a lot of bitmaps drawn on the screen through the Presentation Service, having 2 counts of the service is pretty hard on the heap memory.

**Comment by holyspidoo** [comment]
In fact, connect/disconnect cast device a bunch device and we see a bunch of PresentationService instances in heap dump.

**Comment by entertailion** [comment]
In Android there can only be one instance of a service. Confirm if you are seeing restarts of the service.

**Comment by holyspidoo** [comment]
Through log(tag... I indeed only see one being created (and destroyed).

Apologies for my lack of knowledge on the matter, but is it normal to see this in a heap dump then?
https://goo.gl/photos/Pfw5wJJgJYw5EAqi9

**Comment by holyspidoo** [comment]
So, if I see multiple instances in the heap dump as in the picture above, it does NOTmean I've a memory leak in the service? (like some context within the service that keeps the service alive the way it happens when we leak activities/fragments)

**Comment by entertailion** [comment]
We are investigating and will get back to you.

**Comment by entertailion** [comment]
Our QA team did stress testing to detect leaks and the API looks good. It could just be the Java garbage collector that hasn't kicked in yet since there is enough memory.

**Comment by degemot** [comment]
> Our QA team did stress testing to detect leaks and the API looks good. It could just be the Java garbage collector that hasn't kicked in yet since there is enough memory.

Hallo. Sorry for my question, i realy can't find solution on 5 days.
